name: Update gist with WakaTime summary

on:
  schedule:
    - cron: '0 16 * * *'  # 每天台灣時間 00:00 執行
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update gist
        uses: superman66/wakatime-sync@v1.0.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

